export default {
  product: [
    {
      id: '1',
      productName: 'Astwood Pendant Light',
      images: require('./OurPics/product1.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'The cylinder pendant features a classic design that complements casual and traditional home styles. The hanging light fixture gives you complete control over your lighting.',
      price: '99',
    },

    {
      id: '4',
      productName: 'Westinghouse Lighting 6100800 Fiona',
      images: require('./OurPics/product4.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Evoking warmth and ambiance, this industrial inspired Westinghouse Mini Pendant adds a timeless accent to any decor. The canopy and socket boast a handsome oil rubbed bronze finish.',
      price: '25',
    },
    {
      id: '5',
      productName: '1-Light Mini Pendant Ceiling Fixture',
      images: require('./OurPics/product5.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'This 1-pendants integrated LED light has premium bubble glass with a chrome finish,640 Lumens. Inside the chandelier hanging light has 4000K LED chips offering a neutral white light.',
      price: '69',
    },
    {
      id: '6',
      productName: 'COOSA Hanging Pendant Lighting',
      images: require('./OurPics/product6.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'COOSA Medium Pendant Lighting, Art Glass Vase Shaped Chandelier, Ceiling Light Fixture for Kitchen Dining Room Farmhouse.',
      price: '34',
    },
    {
      id: '7',
      productName: 'LITFAD Antique Lantern Pendant Lighting',
      images: require('./OurPics/product7.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Welcome to visit our store and buy our special designed and good quality products. If you have any questions about our products and please feel free to contact and we will always be here to assist.',
      price: '88',
    },
    {
      id: '8',
      productName: 'KingSo Industrial Metal Pendant Light',
      images: require('./OurPics/product8.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Easy Assembly & Disassembly Design: It allows easy assembly and disassembly, convenient for you to take to your new house when you move. All the 4 light rings are fixed by screws.',
      price: '42',
    },
    {
      id: '9',
      productName: 'Globe Electric Trancoso Pendant Lighting',
      images: require('./OurPics/product9.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'By utilizing natural fibers and a simple but refined style, the Novogratz and Globe Electric have created a serene light that sits in the pocket of the Hygge mind frame.',
      price: '57',
    },
    {
      id: '3',
      productName: 'HMVPL Adjustable Pendant Lighting',
      images: require('./OurPics/product3.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'This hand-finished swag lights will bring your house an elegant and lovely feeling. Invite your friends / family / lover to ensure a cozy time!',
      price: '64',
    },
    {
      id: '10',
      productName: 'ROYAL PEARL Foyer Pendant Light',
      images: require('./OurPics/product10.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'ROYAL PEARL Lighting Limited is a professional home lighting fixtures manufacturer . In order to serve our customers more effectively and produce a wide variety of high-quality products.',
      price: '173',
    },
    {
      id: '11',
      productName: 'Barn Pendant Lights',
      images: require('./OurPics/product11.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Lamp shade inside 3 layer structure. The lamp holder has a vertical protection tube. Light radiates brightly and evenly.',
      price: '32',
    },
    {
      id: '12',
      productName: 'Progress Lighting Staunton Pendants',
      images: require('./OurPics/product12.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Cultivate a timeless lighting design with the Staunton Collection 1-Light Clear Glass Brushed Nickel Vintage Pendant. A light source glows from within a clear glass shade with a chess piece silhouette',
      price: '104',
    },
    {
      id: '13',
      productName: 'LALUZ Industrial Mini Pendant Lighting',
      images: require('./OurPics/product13.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'A surefire shiner, this pendant is perfect above your breakfast table, simply let it hang over a table’s cape of glossy white plates, sleek silverware and tall glasses for an illuminating touch .',
      price: '49',
    },
    {
      id: '14',
      productName: 'HMVPL Pendant Lighting Fixtures',
      images: require('./OurPics/product14.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'This hand-finished swag lights will bring your house an elegant and lovely feeling. Invite your friends / family / lover to ensure a cozy time!',
      price: '74',
    },
    {
      id: '15',
      productName: 'Industrial Pendant Light',
      images: require('./OurPics/product15.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Spherical design: It is especially designed in global shape, perfectly fit your home and make your place look elegant, decent layout meets your high-end needs.',
      price: '43',
    },
    {
      id: '16',
      productName: 'Beam Vintage Ceiling Pendant Lighting',
      images: require('./OurPics/product16.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'An Amazon brand - A modern interpretation of classic vintage design provides style and grace. The rod and hood are metal with oil-rubbed bronze finish and a clear glass shade.',
      price: '69',
    },
    {
      id: '17',
      productName: 'SummitlandAluminum Globe Shaped Pendant',
      images: require('./OurPics/product17.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Here’s a classy favorite: an aluminum globe pendant. Same finish inside and out. It’s institutional, but in a good way. It will play well with your stainless steel appliances, but at a better price.',
      price: '34',
    },
    {
      id: '18',
      productName: 'Royal Pearl Modern 3-Ring LED',
      images: require('./OurPics/product18.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'ROYAL PEARL Lighting Limited is a professional home lighting fixtures manufacturer . In order to serve our customers more effectively and produce a wide variety of high-quality products.',
      price: '239',
    },
    {
      id: '19',
      productName: 'Summitland 14 inch White',
      images: require('./OurPics/product19.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Reminiscent of a tangier cooking pot, this classic white 14 inch pendant with brass inner coating gives off the perfect accent to your updated kitchen or casual dining space.',
      price: '27',
    },
    {
      id: '20',
      productName: 'Artika CHMP-RN Imperium Mid Century Fixture',
      images: require('./OurPics/product20.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Update the look of any room by upgrading your home lighting with this Artika Imperium pendant light. The chandelier-style light brightens up your space with its 9-light design.',
      price: '201',
    },
    // {
    //   id: '21',
    //   productName: 'Progress Lighting P5328-104 Penn Pendants',
    //   images: require('./OurPics/product21.png'),
    //   height: '1.8',
    //   consumption: '36',
    //   watt: '15',
    //   discription:
    //     'The Penn Collection features stylish pendants with a modern take on vintage electric design with clear glass spheres. The Penn Collection will bring high end style to your living space today.',
    //   price: '84',
    // },
    {
      id: '22',
      productName: 'LNC A03291 Pendant Lighting Kitchen Island',
      images: require('./OurPics/product22.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'This concise pendant light with nice design circle shade that gives a simple and charming appeal and adds visual appeal to your decor.',
      price: '70',
    },
    {
      id: '23',
      productName: 'Hobaca Modern Pendant Lights Spot Light',
      images: require('./OurPics/product23.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Base diameter is 6 cm, the Base of this lamp is designed for easy installation on the ceiling, especially the ceiling design without prior reservation of the junction box. You only need to drill a hole.',
      price: '39',
    },
    {
      id: '2',
      productName: 'Licperron Industrial Pendant Light E26',
      images: require('./OurPics/product2.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Licperron specializes in the manufacture of pretty and practical home light fixture with a retro Edison style, designed to add a touch to your home, and improve the quality of life at home.',
      price: '39',
    },
    {
      id: '24',
      productName: 'BELDI 1933-P3 Peak Ceiling Pendant Fixtures',
      images: require('./OurPics/product24.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'The peak collection pendant light is perfect for an island or bar area. Each glass is hand-made and gives a unique touch. This grey pendant will be a focal point wherever located.',
      price: '90',
    },
    {
      id: '25',
      productName: 'Dimmable LED Track Pendant Lighting',
      images: require('./OurPics/product25.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Be sure the electricity to the wires you are working on is shut off; either the fuse is removed or the circuit breaker is turned off. Turning the power off using the light switch is not sufficient to prevent.',
      price: '99',
    },
    {
      id: '26',
      productName: 'Summitland 9 inch Wood Look Pendant Light',
      images: require('./OurPics/product26.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Summitland is proud to present our 9" Wood Look Pendant. With its wood grain finish and acorn shape, this could be the pendant that calls out and defines a living space.',
      price: '39',
    },
    {
      id: '27',
      productName: 'EGLO Westbury Ceiling Pendant Light',
      images: require('./OurPics/product27.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'The Westbury mini pendant by Eglo brings an elegant soft design that will add charm to any indoor living space The steel frame has a painted wood finish which adds a visual distinctive appearance.',
      price: '66',
    },
    {
      id: '28',
      productName: 'Quoizel Grant Vintage Mini Pendant Lighting',
      images: require('./OurPics/product28.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'This opal etched glass fixture is an elegant nod to the past. The classic Americana styling adds a nostalgic flair to your home. When hung over a kitchen island or dinette table it provides ample lighting',
      price: '159',
    },
    {
      id: '29',
      productName: 'Hoocozi Modern Black Gold Pendant Light',
      images: require('./OurPics/product29.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Place two or three hanging light fixtures on your kitchen island, breakfast bar or any type of table to create excellent lighting for the table. Imagine this attractive mini pendant offering',
      price: '35',
    },
    {
      id: '30',
      productName: 'Artika Oracle 5 LED-Integrated Pendant Lamp',
      images: require('./OurPics/product30.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Beautify your home with the daring Oracle 5. Its breathtaking contemporary design allows this suspended luminaire to leave a striking impression on anyone that sets their eyes on it.',
      price: '134',
    },
    {
      id: '31',
      productName: 'Kitchen Island Industrial Pendant Light',
      images: require('./OurPics/product31.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'ADJUSTABLE HEIGHT: Kitchen island pendant light comes with adjustable hanging rod to let you freely determine the height of the lamp.',
      price: '71',
    },
    {
      id: '32',
      productName: 'Artika Melted ICE Pendant LED Light Fixture',
      images: require('./OurPics/product32.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Rustic, industrial, a lighting with character . Whatever the qualifiers used to describe it, one thing is certain: the Melted Ice is an exceptional model to make the whole house shine.',
      price: '216',
    },
    {
      id: '33',
      productName: 'Globe Electric 64906 Edison Pendant Lighting',
      images: require('./OurPics/product33.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        "Globe Electric's simple matte black 1-Light Vintage Edison Mini Pendant with a black designer woven cord is a great spin on a classic design. The exposed socket creates a modern industrial look.",
      price: '12',
    },
    {
      id: '34',
      productName: 'Modern Moravian Star Gold Finish Pendant Light',
      images: require('./OurPics/product34.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Modern Gold Finish Handcrafted Moravian Star Pendant, Art decor Hanging Star Lights Material(s): Alloy, Clear glass and Ceramic Socket for the shade; Solid Metal for the ceiling plate.',
      price: '99',
    },
    {
      id: '35',
      productName: 'Kichler Everly Blown Glass Round Pendant',
      images: require('./OurPics/product35.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'The Everly 15.25” one light bell shaped pendant comes with a curved, glass blown container featuring clear, seeded glass and a Brushed Nickel finish for a simple and elegant look.',
      price: '159',
    },
    {
      id: '36',
      productName: 'Elegant Designs Nautical Ceiling Light Pendant',
      images: require('./OurPics/product36.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        "If you have that lovely beach house, condo, or rental you're looking to decorate, check out this nautical hanging pendant suited for your coastal decor! The aqua glass ball is netted in a natural rope.",
      price: '74',
    },
    {
      id: '37',
      productName: 'Progress Gulliver Five-Light Pendant,Black',
      images: require('./OurPics/product37.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Select the perfect farmhouse home décor with the Gulliver Collection’s Pendant. Bask under the cozy country glow of the light bases grouped at the light fixture’s center ready to hold light sources.',
      price: '248',
    },
    {
      id: '38',
      productName: 'Rivet Industrial Pendant Light Black',
      images: require('./OurPics/product38.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'This modern industrial pendant light features a ridged conical design for the shade that places it firmly in the contemporary style so popular today. The sleek black finish on the cord, fixture.',
      price: '64',
    },
    {
      id: '39',
      productName: 'Chrome Finish Modern Lights Crystal Chandelier',
      images: require('./OurPics/product39.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Feekenbu - Professional Manufacture from China for Crystal Chandelier , Modern Pendant Light , Modern Table Light and Mini Wall Light.',
      price: '89',
    },
    {
      id: '40',
      productName: 'Artika Luxury Pendant Light, Gold',
      images: require('./OurPics/product40.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Luxury is a true standout. Adored by art lovers, the design is minimalist but oh-so impressive. The pendant light features a black & gold finish and luminously design that catch the eye.',
      price: '189',
    },
    {
      id: '41',
      productName: 'Kichler 43224OZ Camerena Chandeliers Lighting',
      images: require('./OurPics/product41.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'The white scavo with light umber inside tinted glass provides a beautiful, ambient lighting to the entire room. Think of it as a foundation or a canvas upon which to paint a distinctive lighting picture.',
      price: '219',
    },
    {
      id: '42',
      productName: 'iYoee LED Kitchen Island Pendant Light',
      images: require('./OurPics/product42.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Easy Assembly & Disassembly Design: It allows easy assembly and disassembly, convenient for you to take to your new house when you move. They can adjust the length.',
      price: '42',
    },
    {
      id: '43',
      productName: 'Progress Lighting P5270-09 Joy Collection',
      images: require('./OurPics/product43.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Gleeful simplicity defines the Joy Collection.Arcing forms of metal and glass are enhanced by a classic finish. Coordinating fixtures from this collection let you decorate an entire home with style.',
      price: '68',
    },
    {
      id: '44',
      productName: 'Newrays Wood Bead Chandelier Pendant Light',
      images: require('./OurPics/product44.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        "Newrays is a lighting brand founded in the United States. What we specialize is European and American artistic lamps'design, production, sale. We are committed to improving the furniture environment.",
      price: '105',
    },
    {
      id: '45',
      productName: 'Westinghouse Lighting 6338400',
      images: require('./OurPics/product45.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'The Westinghouse sophie one-light oil rubbed bronze indoor mini pendant brings impressive style to your home. The beautiful shade adorned with crystal prisms adds a glamorous touch.',
      price: '62',
    },
    {
      id: '46',
      productName: 'Crystal Pendant lights - BAYCHEER Vintage Iron',
      images: require('./OurPics/product46.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Shipped from USA/AMAZON warehouse. The Pendant Lights can be used Indoor Lighting, Warehouse or Barn, and so on, , but we do not recommend for outdoor use.',
      price: '89',
    },
    {
      id: '47',
      productName: 'Industrial Ceiling Lamp Vintage',
      images: require('./OurPics/product47.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'All non-defective, undamaged products must be returned within 30 days after received your Light. All the return items have to keep in good condition and its original package BOX.',
      price: '22',
    },
    {
      id: '48',
      productName: 'GEPOW Industrial Lighting for Kitchen Island',
      images: require('./OurPics/product48.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'An open cage design and exposed light source define the GEPOW pendant collection. Strong geometric lines finished in black surround bulb inside to complete the look.',
      price: '39',
    },
    {
      id: '49',
      productName: 'SOTTAE Modern Black Glass Hanging Pendant',
      images: require('./OurPics/product49.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Modern Small Glass Pendant light is ideal for both household and commercial space,above kitchen island,sink,table and counters,or in bedroom dinning room bars and restaurants.',
      price: '46',
    },
    {
      id: '50',
      productName: 'Hanging Pendant Lighting Fixture',
      images: require('./OurPics/product50.png'),
      height: '1.8',
      consumption: '36',
      watt: '15',
      discription:
        'Contemporary pendant lighting with polish painting aluminum shade.amazon pendant lighting in this price zone. Perfect for your kitchen island or bedroom hanging table lamp.',
      price: '99',
    },
  ],
};
